#!/bin/sh
ssh $SERVER_USER@$SERVER_IP <<EOF  
docker pull $CONTAINER_RELEASE_IMAGE   
docker stop server-production
docker rm server-production
docker run -p 3000:3000 -d --restart always --name server-production $CONTAINER_RELEASE_IMAGE
EOF